kind: Deployment
apiVersion: apps/v1
metadata:
  name: flake-01
  labels:
    app: flake-01

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flake-01
  template:
    metadata:
      labels:
        app: flake-01
    spec:
      containers:
        - name: flake-01
          image: ghcr.io/tinogoehlert/k8samples/hello-web:main
          ports:
            - name: web
              containerPort: 8080
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /healthzasfdsfaw
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 3
