kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-web
  labels:
    app: hello-web

spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-web
  template:
    metadata:
      labels:
        app: hello-web
    spec:
      containers:
        - name: hello-web
          image: ghcr.io/tinogoehlert/k8samples/hello-web:main
          ports:
            - name: web
              containerPort: 8080
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-web

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: hello-web
